{{- if $.Values.server.enabled }}
{{- range $service := (list "frontend" "history" "matching" "worker") }}
{{- $serviceValues := index $.Values.server $service -}}
{{- if $serviceValues.autoscaling.enabled }}
apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "temporal.componentname" (list $ $service) }}
  labels:
    app.kubernetes.io/name: {{ include "temporal.name" $ }}
    helm.sh/chart: {{ include "temporal.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: {{ $service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "temporal.componentname" (list $ $service) }}
  minReplicas: {{ $serviceValues.autoscaling.minReplicas }}
  maxReplicas: {{ $serviceValues.autoscaling.maxReplicas }}
  metrics:
    {{- if $serviceValues.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" $) }}
        targetAverageUtilization: {{ $serviceValues.autoscaling.targetCPU }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ $serviceValues.autoscaling.targetCPU }}
        {{- end }}
    {{- end }}
    {{- if $serviceValues.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" $) }}
        targetAverageUtilization: {{ $serviceValues.autoscaling.targetMemory }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ $serviceValues.autoscaling.targetMemory }}
        {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
